@startuml
class PaperServices{
-double OVERDUE_FEE
-int daysPastDue
-double bill
-double change

+AccountBalance()
+AccountBalance(int daysPastDue)
+void setDaysPastDue(int daysPastDue)
+double getOverDueBookBalance()
+double payBalance(double payment)
+double giveChange()
}


@enduml
